<?php

namespace App\Models\Post;

use App\Models\Customer\Customer;
use App\Models\Stores\Store;
use App\Scopes\PostScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    protected $table='posts';
    protected $fillable=['id','image','is_active','is_approved'];
//    protected $hidden=['pivot'];

    // locale scope
    public function scopeIsActive($query)
    {
        return $query->where('is_active',1)->get();
    }

    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new PostScope());
    }

    public function PostTranslation()
    {
        return $this->hasMany(PostTranslation::class);
    }

    public function Store()
    {
        return $this->belongsToMany(Store::class,'post_store','post_id','store_id','id','id');
    }

    public function Customer()
    {
        return $this->belongsToMany(Customer::class,'post_customer','post_id','customer_id','id','id');
    }
}
