<?php

namespace App\Models\Customer;

use App\Models\Doctors\doctor;
use App\Models\Customer\CustomerTranslation;
use App\Models\Doctors\DoctorCustomer;
use App\Scopes\CustomerScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Config;

class Customer extends Model
{
    use HasFactory;
    protected $table='customers';
    protected $fillable=['id','social_media_id','is_active','is_approved'];
    protected $hidden=['created_at','updated_at','social_media_id'];
    //scope
//    public function ScopeIsActive($query)
//    {
//        return $query->where('is_active',1);
//    }
    protected static function booted()
    {
        parent::booted(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new CustomerScope);
    }

    public function ScopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }

    public function customerTranslation()
    {
        return $this->hasMany(customerTranslation::class);
    }

    public function doctor()
    {
        return $this->belongsToMany(doctor::class,'customer_doctor')
                    ->using(DoctorCustomer::class)
                    ->withPivot(['medical_file_id','age','gender','social_status'
                                    ,'blood_type','note','is_active','is_approved']);
    }
}
