<?php

namespace App\Models\MenuType;

use App\Models\Menu\Menu;
use App\Scopes\MenuTypeScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MenuType extends Model
{
    use HasFactory;

    protected $table='menu_types';
    protected $fillable=['id','image','is_active','is_approved'];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new MenuTypeScope());
    }

    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }
    public function MenuTypeTranslation()
    {
        return $this->hasMany(MenuTypeTranslation::class);
    }
    public function Menu()
    {
        return $this->hasMany(Menu::class);
    }

}
