<?php

namespace App\Models\RestaurantCategory;

use App\Models\Item\Item;
use App\Models\Restaurant\Restaurant;
use App\Models\RestaurantProduct\RestaurantProduct;
use App\Scopes\RestaurantCategoryScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RestaurantCategory extends Model
{
    use HasFactory;
    protected $table='restaurant_categories';
    protected $fillable=['id','image','is_active','is_approved'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new RestaurantCategoryScope());
    }
    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }


    public function restaurantCategoryTranslation()
    {
        return $this->hasMany(RestaurantCategoryTranslation::class);
    }

    public function category()
    {
        return $this->belongsToMany(RestaurantCategory::class);
    }

    public function Restaurant()
    {
        return $this->belongsToMany(Restaurant::class,'restaurant_restaurant_category','restaurant_category_id','restaurant_id','id','id');
    }
    public function RestaurantProduct()
    {
        return $this->belongsToMany(RestaurantProduct::class,'restaurant_category_restaurant_product','restaurant_category_id','restaurant_product_id','id','id');
    }
    public function Item()
    {
        return $this->belongsToMany(Item::class,'restaurant_category_item','restaurant_category_id','item_id','id','id');
    }
}
