<?php

namespace App\Models\RestaurantCategory;

use App\Models\Item\Item;
use App\Models\Restaurant\Restaurant;
use App\Models\RestaurantProduct\RestaurantProduct;
use App\Scopes\RestaurantCategoryScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RestaurantCategory extends Model
{
    use HasFactory;
    protected $table='restaurant_categories';
    protected $fillable=['id','image','is_active','is_approved'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new RestaurantCategoryScope());
    }
    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }


    public function restaurantCategoryTranslation()
    {
        return $this->hasMany(RestaurantCategoryTranslation::class);
    }

    public function Restaurant()
    {
        return $this->belongsToMany(Restaurant::class);
    }
    public function RestaurantProduct()
    {
        return $this->hasMany(RestaurantProduct::class);
    }
    public function Item()
    {
        return $this->hasMany(Item::class);
    }
}
