<?php

namespace App\Models\RestaurantProduct;

use App\Models\Item\Item;
use App\Models\Restaurant\Restaurant;
use App\Models\RestaurantCategory\RestaurantCategory;
use App\Scopes\RestaurantProductScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RestaurantProduct extends Model
{
    use HasFactory;
    protected $table='restaurant_products';
    protected $fillable=['id','image','is_active','is_approved'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new RestaurantProductScope());
    }
    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }

    public function restaurantProductTranslation()
    {
        return $this->hasMany(RestaurantProductTranslation::class);
    }

    public function Restaurant()
    {
        return $this->belongsToMany(Restaurant::class,'restaurant_restaurant_product','restaurant_product_id','restaurant_id','id','id');
    }
    public function RestaurantCategory()
    {
        return $this->belongsToMany(RestaurantCategory::class,'restaurant_category_restaurant_product','restaurant_product_id','restaurant_category_id','id','id');
    }
    public function Item()
    {
        return $this->hasMany(Item::class);
    }

}
