<?php

namespace App\Models\Item;

use App\Models\Restaurant\Restaurant;
use App\Models\RestaurantCategory\RestaurantCategory;
use App\Models\RestaurantProduct\RestaurantProduct;
use App\Scopes\ItemScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $table='items';
    protected $fillable=['id','product_id','image','is_active','is_approved'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ItemScope());
    }
    public function Restaurant()
    {
        return $this->belongsToMany(Restaurant::class);
    }
    public function RestaurantCategory()
    {
        return $this->belongsToMany(RestaurantCategory::class);
    }
    public function RestaurantProduct()
    {
        return $this->belongsTo(RestaurantProduct::class);
    }

}
