<?php

namespace App\Models\Item;

use App\Models\Restaurant\Restaurant;
use App\Models\RestaurantCategory\RestaurantCategory;
use App\Models\RestaurantProduct\RestaurantProduct;
use App\Scopes\ItemScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $table='items';
    protected $fillable=['id','restaurant_product_id','image','is_active','is_approved'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ItemScope());
    }

    public function scopeNotActive($quere)
    {
        return $quere->where('is_active',0)->get();
    }
    public function ItemTranslation()
    {
        return $this->hasMany(ItemTranslation::class);
    }
    public function Restaurant()
    {
        return $this->belongsToMany(Restaurant::class,'restaurant_item','item_id','restaurant_id','id','id');
    }


}
