<?php

namespace App\Models\Menu;

use App\Models\MenuType\MenuType;
use App\Models\Restaurant\restaurant;
use App\Scopes\MenuScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;
    protected $table='menus';
    protected $fillable=['id','image','menu_type_id','restaurant_id','is_active','is_approved'];
    protected $hidden=['menu_type_id','restaurant_id','created_at','updated_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new MenuScope());
    }

    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }

    public function MenuTranslation()
    {
        return $this->hasMany(MenuTranslation::class);
    }

    public function restaurant()
    {
        return $this->belongsTo(restaurant::class);
    }
    public function MenuType()
    {
        return $this->belongsToMany(MenuType::class);
    }


}
