<?php

namespace App\Models\Menu;

use App\Models\Item\Item;
use App\Models\Restaurant\Restaurant;
use App\Scopes\MenuScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Menu extends Model
{
    use HasFactory;
    use Notifiable;

    protected $table='menus';
    protected $fillable=['id','image','is_active','is_approved'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new MenuScope());
    }
    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }


    public function MenuTranslation()
    {
        return $this->hasMany(MenuTranslation::class);
    }

    public function Menu()
    {
        return $this->belongsToMany(Menu::class);
    }

    public function Restaurant()
    {
        return $this->belongsToMany(Restaurant::class,'restaurant_menu','menu_id','restaurant_id','id','id');
    }

//    public function Item()
//    {
//        return $this->belongsToMany(Item::class,'restaurant_category_item','restaurant_category_id','item_id','id','id');
//    }
}
