<?php

namespace App\Models\RestaurantType;

use App\Models\Restaurant\Restaurant;
use App\Scopes\RestaurantTypeScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RestaurantType extends Model
{
    use HasFactory;
    protected $table='restaurant_types';
    protected $fillable =['Id','image','is_active','is_approved','restaurant_id'];
    public $timestamps=false;
    protected $hidden=['created_at','updated_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new RestaurantTypeScope());
    }

    public function scopeNotActive($query)
    {
        return $query->where('is_active',0)->get();
    }


    public function restaurantTypeTranslation()
    {
        return $this->hasMany(RestaurantTypeTranslation::class);
    }

    public function restaurant()
    {
        return $this->belongsToMany(Restaurant::class);
    }
}
